# Generated by Django 4.2.7 on 2024-02-10 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='normUser',
            fields=[
                ('username', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('profilePic', models.ImageField(null=True, upload_to='profilePics/')),
                ('securityQuestion', models.TextField(max_length=60)),
                ('secAnswer', models.TextField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
