# Generated by Django 4.2.7 on 2024-02-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normuser',
            name='userId',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='normuser',
            name='username',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
