# Generated by Django 4.2.7 on 2024-02-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_feedbacks_alter_normuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='filelocation',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='time',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='annonuser',
            field=models.TextField(default='*user*'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='content',
            field=models.TextField(default='this is the default message'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='created_at',
            field=models.TextField(default='0000-00-00'),
        ),
    ]
