# Generated by Django 4.2.7 on 2024-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
