# Generated by Django 4.2.7 on 2024-02-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_user_contact_user_email_alter_feedbacks_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='profilePics/'),
        ),
    ]
